// CommonJS, every file is module (by default)
// Modules - Encapsulated code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utilies')
const data = require('./6-alternative-flavore')

console.log(data)
require('./7-mind-grenade')
sayHi("bero")
sayHi(names.john)
sayHi(names.peter)